# ESPHome HLK-LD2450 Minimal Configuration
# Optimiert für ESP32-C3 Super Mini mit MQTT (ioBroker)
# Max. 3 Targets: X, Y, Speed, Distance, Angle
#
# SETUP: 
# 1. Kopiere example-secrets.yaml nach secrets.yaml
# 2. Fülle secrets.yaml mit deinen Credentials aus
# 3. esphome run ld2450-minimal.yaml

esphome:
  name: ld2450-minimal
  friendly_name: "LD2450 Presence"
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_flash: 40000000L

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Logger (UART deaktiviert - wird für Sensor verwendet)
logger:
  level: INFO
  baud_rate: 0

# WiFi - ESP32-C3 optimiert
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5dBm
  power_save_mode: NONE
  fast_connect: true
  ap:
    ssid: "c3-wifi-test-fallback"
    password: ""

# MQTT für ioBroker
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

# OTA Updates
ota:
  password: !secret ota_password

captive_portal:

# UART für HLK-LD2450
uart:
  id: uart_ld2450
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

# Externe Komponente
external_components:
  - source:
      type: local
      path: components

# LD2450 Sensor - Minimale Konfiguration
LD2450:
  uart_id: uart_ld2450
  name: "Presence"
  flip_x_axis: false
  fast_off_detection: true
  
  # Occupancy (binary_sensor)
  occupancy:
    name: "Occupancy"
  
  # Target Count (sensor)
  target_count:
    name: "Target Count"
  
  # 3 Targets mit X, Y, Speed, Distance, Angle
  targets:
    - target:
        name: "Target 1"
        x_position:
          name: "X"
        y_position:
          name: "Y"
        speed:
          name: "Speed"
        distance:
          name: "Distance"
        angle:
          name: "Angle"
    - target:
        name: "Target 2"
        x_position:
          name: "X"
        y_position:
          name: "Y"
        speed:
          name: "Speed"
        distance:
          name: "Distance"
        angle:
          name: "Angle"
    - target:
        name: "Target 3"
        x_position:
          name: "X"
        y_position:
          name: "Y"
        speed:
          name: "Speed"
        distance:
          name: "Distance"
        angle:
          name: "Angle"

  # Number-Entities
  max_detection_distance:
    name: "Max Distance"
    initial_value: 6m
    step: 0.1m
  
  max_detection_tilt_angle:
    name: "Max Tilt Angle"
    initial_value: 60°
    step: 1°
    
  min_detection_tilt_angle:
    name: "Min Tilt Angle"
    initial_value: -60°
    step: 1°

  # Tracking Mode Switch
  tracking_mode_switch:
    name: "Multi-Target Mode"
  
  # Restart Button
  restart_button:
    name: "Restart Sensor"
