# ESPHome HLK-LD2450 mmWave Presence Sensor
# Optimiert für ESP32-C3 Super Mini mit MQTT (ioBroker)
# 
# WICHTIG: Erstelle eine secrets.yaml basierend auf example-secrets.yaml

esphome:
  name: ld2450-presence
  friendly_name: "LD2450 Presence Sensor"
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_flash: 40000000L

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Logger
logger:
  level: DEBUG
  baud_rate: 0  # Disable UART logging (we use UART for sensor)

# WiFi Konfiguration - ESP32-C3 optimiert gegen -127 dB Problem
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5dBm  # Kritisch für ESP32-C3 Mini!
  power_save_mode: NONE  # Kein Power-Save für stabile Verbindung
  fast_connect: true     # Schnellere Verbindung
  
  # Fallback AP
  ap:
    ssid: "LD2450-Fallback"
    password: !secret ap_password

# MQTT für ioBroker Integration
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

# OTA Updates
ota:
  password: !secret ota_password

# Captive Portal für Fallback
captive_portal:

# UART für HLK-LD2450
uart:
  id: uart_ld2450
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

# Externe Komponente
external_components:
  - source:
      type: local
      path: components

# LD2450 Sensor Konfiguration
LD2450:
  uart_id: uart_ld2450
  name: "Presence"
  flip_x_axis: false
  fast_off_detection: true
  
  # Global Occupancy Sensor
  occupancy:
    name: "Occupancy"
  
  # Target Count Sensor  
  target_count:
    name: "Target Count"
  
  # Targets (max 3)
  targets:
    - target:
        name: "Target 1"
        x_position:
          name: "Target 1 X"
        y_position:
          name: "Target 1 Y"
        speed:
          name: "Target 1 Speed"
        distance:
          name: "Target 1 Distance"
        angle:
          name: "Target 1 Angle"
    - target:
        name: "Target 2"
        x_position:
          name: "Target 2 X"
        y_position:
          name: "Target 2 Y"
        speed:
          name: "Target 2 Speed"
        distance:
          name: "Target 2 Distance"
        angle:
          name: "Target 2 Angle"
    - target:
        name: "Target 3"
        x_position:
          name: "Target 3 X"
        y_position:
          name: "Target 3 Y"
        speed:
          name: "Target 3 Speed"
        distance:
          name: "Target 3 Distance"
        angle:
          name: "Target 3 Angle"

  # Einstellbare Limits
  max_detection_distance:
    name: "Max Distance"
    initial_value: 6m
    step: 0.1m
  
  max_detection_tilt_angle:
    name: "Max Tilt Angle"
    initial_value: 60°
    step: 1°
    
  min_detection_tilt_angle:
    name: "Min Tilt Angle"
    initial_value: -60°
    step: 1°

  # Tracking Mode Switch
  tracking_mode_switch:
    name: "Multi-Target Mode"
  
  # Restart Button
  restart_button:
    name: "Restart Sensor"
